spring.datasource.url=mysql://root:XiRGrOEOQkPNddTgBXWHpIapwYLUZUip@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=XiRGrOEOQkPNddTgBXWHpIapwYLUZUip

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key=sk-ijkl1234ijkl1234ijkl1234ijkl1234ijkl1234